### ISSUE TITLE
Error: MQTT is not configured for AWS

### ISSUE THREAD

**Issue by praveeno** [PatrickSteiner/Google_Cloud_IoT_Demo#2]
![](https://user-images.githubusercontent.com/36146388/39577295-88946550-4efe-11e8-944a-701668bea8e7.png)

Hello, I found this tutorial very useful, I following all steps but got this

**Comment by PatrickSteiner** [comment]
Looks like you forget to register the ESP with Cloud IoT Core as described in https://github.com/PatrickSteiner/Google_Cloud_IoT_Demo#connect-esp8266-to-google-cloud
