### ISSUE TITLE
[FAQ] python version dataflow java programs

### ISSUE THREAD

**Issue by kirantpatil** [PatrickSteiner/Google_Cloud_IoT_Demo#3]
Hi,

I am ruby programmer planning to learn python.

I would like to know do I need to learn Java or I can manage with python alone ?

Also, would like to know if you have the python version of dataflow java programs.

Thanks,
Kiran.

**Comment by PatrickSteiner** [comment]
I'm neither Python nor Ruby experience, so can't tell.

If you look at the Dataflow documentation, you might find ways to easily transfer the sample.

**Comment by kirantpatil** [comment]
Thank you.
