### ISSUE TITLE
How to create dynamic table using Device-id ?

### ISSUE THREAD

**Issue by kirantpatil** [PatrickSteiner/Google_Cloud_IoT_Demo#4]
Hi,

From your code I made following changes and defined global variable ""avgSpeedTable" for table name and I am trying to construct it at "FormatAsTableRowFn" as below but it is not getting reflected at "main" function and passing "null". So I am getting "Null-pointer exception".

Please guide me to resolve this challenge.

### Error message, I printed the value of avgSpeedTable to verify and it is having "null". So the culprit is avgSpeedTable variable
```

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project second-dataflow: An exception occured while executing the Java class. null: InvocationTargetException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (default-cli) on project second-dataflow: An exception occured while executing the Java class. null
```

Note:  I am newbie to Java

### FormatAsTableRowFn function

                                String device = (String)jsonMessage.get("Device-id");
                                avgSpeedTable =  "brss-711:demos." + device;

### main function

                p.apply(PubsubIO.readStrings().fromTopic(options.getPubSubTopic()))
                 .apply(ParDo.of(new FormatAsTableRowFn()))
                 .apply(BigQueryIO.writeTableRows().to(avgSpeedTable.toString())
                          .withSchema(schema)
                          .withWriteDisposition(BigQueryIO.Write.WriteDisposition.WRITE_APPEND)
                          .withCreateDisposition(BigQueryIO.Write.CreateDisposition.CREATE_IF_NEEDED));

Regards,
Kiran.

**Comment by kirantpatil** [comment]
Please find the attached whole file.

[PubSubReader.zip](https://github.com/PatrickSteiner/Google_Cloud_IoT_Demo/files/2187943/PubSubReader.zip)

**Comment by PatrickSteiner** [comment]
I'm sorry, but due to other tasks, I will not be able to look at this in the near future. Sorry!

**Comment by kirantpatil** [comment]
Hi @PatrickSteiner,

Sorry for not closing this issue, I resolved this issue by using "[Dynamic Destinations](https://beam.apache.org/documentation/sdks/javadoc/2.2.0/org/apache/beam/sdk/io/gcp/bigquery/DynamicDestinations.html)".

Thanks.
